### ISSUE TITLE
Pymesh pip package is different from what is actually intended for use in the codebase

### ISSUE THREAD

**Issue by saurabh1002** [danielegrattarola/GINR#1]
The pip package listed below is from [this repo](https://github.com/taxpon/pymesh), which does not provide the functions and api used in your codes.
https://github.com/danielegrattarola/GINR/blob/1d0d17d6b0bf2d3588e490892076ca5958bc3a35/requirements.txt#L9

I believe that your target library pymesh is [this repository](https://github.com/PyMesh/PyMesh), which unfortunately does not have a pip package pre-baked, and requires to build from source.

I have made a PR to resolve this error

**Comment by danielegrattarola** [comment]
Thanks, I think we can move the discussion to the PR in the meantime.
