### ISSUE TITLE
Does us_elections have evluation?

### ISSUE THREAD

**Issue by cyang810** [danielegrattarola/GINR#5]
Dear author. First I want to express my sincere gratitude for open-sourcing your work. While working with the us_elections dataset, I couldn't find the evaluation code. I was wondering if there's no need for evaluation on this dataset? I would greatly appreciate your response.

**Comment by danielegrattarola** [comment]
Hello, 

what do you mean by the dataset's evaluation?

Cheers

**Comment by cyang810** [comment]
Thank you for your reply. I cannot find the command to evaluate the 'us_election' dataset in 'command_evaluation.sh'. if there's no need for evaluation on this dataset? Looking forward to your reply.

**Comment by danielegrattarola** [comment]
I'm sorry, I misunderstood your first question. 
The command is not included in the eval file because the eval of the base GINR experiment only consists of plotting the learned signal. US Election cannot be plotted, so there is no eval command.

**Comment by cyang810** [comment]
Thank you for your reply

**Comment by cyang810** [comment]
Thank you
